version: '3'

services:
 app:
   container_name: rest-api
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     PORT: "80"
   ports:
     - 80:80
 db:
   container_name: postgres
   image: postgres:15.4-alpine3.18
   environment:
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_DB: ${POSTGRES_DB}